### ISSUE TITLE
BDP-105 compatibility ?

### ISSUE THREAD

**Issue by vincegre** [simbaja/ha_oppoudp#2]
Hi

I'm trying to use your integration with a BDP-105 that is supposed to be compatible with the network protocol but I can't get communication to work. Do you know if it's compatible ?

Thanks

Vincèn

**Comment by simbaja** [comment]
I think they subtly changed things between the models.  I do recall seeing that the 1xx series was also on a different port by default, might be 48360.  Try http://www.remotecentral.com/cgi-bin/mboard/rs232-ip/thread.cgi?746 for more ideas potentially.

**Comment by vincegre** [comment]
> I think they subtly changed things between the models. I do recall seeing that the 1xx series was also on a different port by default, might be 48360. Try http://www.remotecentral.com/cgi-bin/mboard/rs232-ip/thread.cgi?746 for more ideas potentially.

Thanks for info and sorry for late answer as I could not test it before :( On BDP-105 port 48360 is open, integration accepts it but it controls nothing, I guess it was using a variant of Oppo protocol so not working unhappy with your integration :( Will go for IR commands...
