### ISSUE TITLE
Integration broken in Home Assistant update 2023.6.0

### ISSUE THREAD

**Issue by 35gh** [simbaja/ha_oppoudp#3]
Since I've updated Home Assistant to 2023.6.0, this integration does not longer work.

My Oppo 203 player becomes unavailable every minute for 15 seconds.
<img width="1628" alt="Capture d’écran 2023-06-08 à 13 39 52" src="https://github.com/simbaja/ha_oppoudp/assets/90415090/aa67bc8e-554f-49bf-9e3d-2b6f8a373bc1">

I see this warning in the logs:
`Logger: oppoudpsdk.client`
`Source: runner.py:179`
`First occurred: 08:51:54 (5802 occurrences)`
`Last logged: 13:42:22`
`Multiple timeouts while waiting for command response, will disconnect and retry.`

Thanks.

**Comment by simbaja** [comment]
with any luck it works now, but let me know if it doesn't

**Comment by 35gh** [comment]
I've updated to v0.1.18 and it seems to work now, thanks!

**Comment by LeoeLeoeL** [comment]
It works.
Tks.
